### ISSUE TITLE
git clone failed，not have correct access rights of git@bitbucket

### ISSUE THREAD

**Issue by shrek-fu** [UBCSailbot/obstacle-detection#24]
when I execute “git submodule update --init --recursive” 
and the console cout：
Submodule path 'lib/jsoncpp': checked out '4356d9bba191e1e16ce7a92073cbf3e63564e973'
Cloning into 'lib/protofiles'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@bitbucket.ubcsailbot.org:7999/fw/protofiles.git' into submodule path 'lib/protofiles' failed

Could you help me  solve this problem？
I’m looking forward your reply.thank you！！

**Comment by pcernek** [comment]
hi @shrek-fu , that bitbucket repository is not public. I've copied the missing submodule into this repository, which should solve your issue.
